### ISSUE TITLE
Is it possible to show thumbnails of photos in gallery view?

### ISSUE THREAD

**Issue by josthkko** [jdriscoll/django-photologue#116]
In the bottom field, where you can select images to add to the gallery, is it possible to show not just names, but also the thumbnails? I would really need to know, at least just how to enable that myself.
@jdriscoll, thanks!

**Comment by richardbarran** [comment]
Hi @josthkko,
Did you ever modify the template used by sortedm2m to add thumbnails?
I am going to close this ticket for now as it's a change in a 3rd party library, rather than in Photologue itself.
