### ISSUE TITLE
Rotation based on EXIF before or after resize ?

### ISSUE THREAD

**Issue by nim65s** [jdriscoll/django-photologue#123]
The issue #122 has been fixed by rotating the images just after the resize step, so it does not follow the width/height rules defined in photosize anymore (for non-square ones).

@mathieuhinderyckx : Was there a good reason do to so ?

**Comment by mathieuhinderyckx** [comment]
@nim65s There was no good reason to do so. I basically just placed it somewhere soon in the chain, and didn't notice that problem. Looking at it, it should indeed better be placed aboce the resize step.

**Comment by nim65s** [comment]
@mathieuhinderyckx ok, thanks.

And did you tried this code ? It looks good, but seems to mirror all the miniatures of my pictures :/

**Comment by h4nz1** [comment]
I've got same problem. Some of the thumbnails are mirrored. How to solve this problem, pls? Thanks

**Comment by nim65s** [comment]
https://github.com/jdriscoll/django-photologue/pull/127 fixed that for me

**Comment by richardbarran** [comment]
Hi all,
Sorry for the slow response - been very busy with a house move.
I am going to assume that #127 fixed this issue, and I am going to close it.
