### ISSUE TITLE
0002 South data migration assumes titles won't end in numbers

### ISSUE THREAD

**Issue by christopherhan** [jdriscoll/django-photologue#124]
PR #53  introduced a bug that assumes Gallery and Photo titles won't end in numbers. For example, if I have a photo with a title *I-405 Closure Construction Photos, Sept 28-30 (6223)*

This would get truncated to *I-405 Closure Construction Photos, Sept 28-30 (622* by [this line](https://github.com/jdriscoll/django-photologue/blob/master/photologue/south_migrations/0002_auto__chg_field_gallery_title__chg_field_galleryupload_title__chg_fiel.py#L38)

The last digit is then incremented by 1, and the final title would be *I-405 Closure Construction Photos, Sept 28-30 (623*

This will lead to a uniqueness problem if I have more than 9 photos that start with *I-405 Closure Construction Photos, Sept 28-30 (62*

A better nomenclature should be implemented to ensure uniqueness.

**Comment by richardbarran** [comment]
Well spotted - there is a bug in that South migration script.

I looked a bit deeper into the impact of this bug:
- It only affects projects that use Django 1.6 (Django 1.7 and higher no longer use South).
- Django 1.8 is already in alpha; when it is released, Django 1.6 will be end-of-life, and there will be no reason for Photologue to support South.
- It will only affect projects on Photologue 2.5 and earlier, which have existing data with titles at least 50 chars long.

I would think that the probability of it affecting another project is pretty low :-) so I will close this issue as a "won't fix". On the other hand, if you want to code a bug fix and send in a pull request, I will of course incorporate it.

**Comment by christopherhan** [comment]
Makes sense. We are upgrading from an really old install to the latest. We just renamed all of our galleries to be less than 50 characters since we needed more intelligent titles than truncating the title. Also note that there is another bug when the photos are being renamed - it doesn't check for title length before truncating it like it does for galleries so all Photo objects end up with a number appended to it.  Maybe add a note in the docs so it doesn't catch anyone by surprise?

Just commenting on my findings in case someone else runs into this problem.
