### ISSUE TITLE
Portrait photos switching to landscape automatically

### ISSUE THREAD

**Issue by edgecaselabs** [jdriscoll/django-photologue#129]
I have some portrait photos (960w x 1280h) that I'm running thru a Photo Size of 944 width and 400 height. I have upscale, crop, and pre-cached all checked.

The resized photo is rotated 90 degrees counter-clockwise and I don't know why.

This happens with quite a few photos. The stored originals are still the correct orientation, so this is something with the image processor making the decision to do the rotation.

**Comment by edgecaselabs** [comment]
*crickets*


Really? I'm the only one who's getting this? :-)

**Comment by richardbarran** [comment]
Maybe the images are rotated based on EXIF data?
There's a fix for this on the master branch - see https://github.com/jdriscoll/django-photologue/commit/7cad9750cd4ee6c2ee143c5a237da55f9137017e - but it has not been released yet.
Maybe you could try running the master branch of Photologue and see if it fixes your issue?

**Comment by edgecaselabs** [comment]
That would make sense. I think this photo is off an iPhone so it could have some orientation data based on the phone's gyros. I'll try this today!

**Comment by edgecaselabs** [comment]
That did the trick! Thanks

**Comment by richardbarran** [comment]
That's great to hear.
I have just released Photologue 3.2 which includes this fix, so I can now close this issue.
