### ISSUE TITLE
DEBUG = False issue

### ISSUE THREAD

**Issue by camara-** [jdriscoll/django-photologue#130]
on a live website when I turn off debug, all pictures that were uploaded when DEBUG= True don't load. 

Same SITE_ID.

**Comment by richardbarran** [comment]
Hi Camara,
If I understand correctly, on the live website, the pictures display correctly if DEBUG=True, but you get 404s if DEBUG=False?

**Comment by camara-** [comment]
Actually that was a problem from my end, I didn't set up the URLs.py file to serve media correctly when DEBUG=False. I thought it was a photologue issue because all media wasn't rendering, and all were basically Photoluge's.

**Comment by richardbarran** [comment]
Ok - issue with project settings, not with Photologue.
I will close this ticket.
