### ISSUE TITLE
New project fails

### ISSUE THREAD

**Issue by blacktav** [jdriscoll/django-photologue#131]
Hi 

I am getting the following error regardless of python2/3 or django 1.7/1.8; originally it happened after I added photologue to an active project but I am getting it even on a fresh project when photologue & stortedm2m are added as INSTALLED_APPS. Errors below are with a clean django 1.8 install on python 2.7 with 

Django-1.8.dist-info
django_model_utils-2.2-py2.7.egg-info
django_photologue-3.1.1-py2.7.egg-info
django_sortedm2m-0.9.5-py2.7.egg-info

(tip)[drew@blacktav pit]$ python manage.py migrate
/secure/Shares/drew/Develop/Django/tip/lib/python2.7/site-packages/django/contrib/sites/models.py:78: RemovedInDjango19Warning: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Site(models.Model):

SystemCheckError: System check identified some issues:

ERRORS:
photologue.Gallery.sites: (fields.E300) Field defines a relation with model 'Site', which is either not installed, or is abstract.
photologue.Photo.sites: (fields.E300) Field defines a relation with model 'Site', which is either not installed, or is abstract.

WARNINGS:
photologue.Gallery.photos: (fields.W340) null has no effect on ManyToManyField.
photologue.Gallery.sites: (fields.W340) null has no effect on ManyToManyField.
photologue.Photo.sites: (fields.W340) null has no effect on ManyToManyField.

**Comment by blacktav** [comment]
The main problem was I had failed to include django.contrib.sites and other settings

The warnings remain though

**Comment by agalitsyn** [comment]
Hi, guys

Env: django 1.7.7, py27

I had the same error, and I was followed by https://django-photologue.readthedocs.org/en/3.1/pages/installation.html#installation

So, why we can't put dependence on 'django.contrib.sites' in docs?

**Comment by int3grate** [comment]
As a new Django user, I ran into the same issue.  Took a bit of head banging to figure it out.  I agree with agalitsyn, this should definitely be documented.

**Comment by richardbarran** [comment]
Hey guys, the installation docs **do** [mention the Sites framework](https://django-photologue.readthedocs.org/en/stable/pages/installation.html#configure-your-django-settings-file) ;-)

However, as several people have raised this issue, maybe the instructions were not clear - [I've tried to rephrase them](http://django-photologue.readthedocs.org/en/latest/pages/installation.html#configure-your-django-settings-file); suggestions/comments on how to improve this part of the documentation are welcome.
