### ISSUE TITLE
Thumbnail PhotoSizes should default to increment_count=False

### ISSUE THREAD

**Issue by evgeni** [jdriscoll/django-photologue#133]
Hi,

when displaying a `GalleryDetailView` of a Gallery with a few hundred of pictures (I tested 500), the view is really slow to render, as it will call `get_thumbnail_size` for each picture, which will (by default) increment the counter and re-save, producing a database commit for each and every picture.

While this is fine for individual pictures, I think "thumbnail" and "admin_thumbnail" should have `increment_count=False` by default.

Regards
Evgeni

**Comment by richardbarran** [comment]
Sounds like a very sensible idea! I have updated the initial setup of the Photosizes.
