### ISSUE TITLE
Invalid format string in error message

### ISSUE THREAD

**Issue by akaihola** [jdriscoll/django-photologue#138]
The format string in [forms.py:139](/jdriscoll/django-photologue/blob/96cf522a1c9edde36c442a7e5af31f79e1076e41/photologue/forms.py#L139) mixes old Python string interpolation and `.format()` syntax:

    messages.warning(request,
                     _('Did not create photo "%(filename)s" with slug "{1}" as a photo with that '
                       'slug already exists.').format(filename, slug),
                     fail_silently=True)

**Comment by richardbarran** [comment]
Oops! Will have to fix that! Thanks for the bug report.

**Comment by richardbarran** [comment]
Thanks for the report - it made me realise that that part of the code was actually wrong, so I fixed it in commit 2bb59639e96eaa1b3db0f5dbf13420caef8c551f.
I'm closing this ticket now as it's no longer valid :-)
