### ISSUE TITLE
Zip upload uses gallery title instead of "Title" field for photos

### ISSUE THREAD

**Issue by akaihola** [jdriscoll/django-photologue#139]
In [forms.py:130](/jdriscoll/django-photologue/blob/96cf522a1c9edde36c442a7e5af31f79e1076e41/photologue/forms.py#L130), the Zip file upload builds the photo title from the title of the selected gallery and a running number, instead of using the value of the "Title" form field:

    title = ' '.join([gallery.title, str(count)])

**Comment by richardbarran** [comment]
Fixed - thanks for the bug report.
