### ISSUE TITLE
Gallery add photo always keeps only one photo

### ISSUE THREAD

**Issue by kanhaiyakumawat** [jdriscoll/django-photologue#141]
I have 3 pics added through admin. Now if I select more than 1 pics at a time to be added to gallery, only the first one gets added to gallery. So basically I am not able to add more than 1 pic in gallery. But same works in my local environment. I am using heroku as my production host and using AWS to host the files.

**Comment by richardbarran** [comment]
Hi,
It could be an error in the Javascript that controls adding Photos to a Gallery - if you still have this issue, could you try running your browser while checking for errors (e.g. on Chrome: View > Developer > Javascript Console)?

**Comment by kanhaiyakumawat** [comment]
Thanks Richard for your response.

Looks like this happened as my website was getting served from https (heroku) while the URLs for photologue were using http. I disabled the security warning from browser and it worked fine. For now I am closing the issue, but if some option for choosing 'http' or 'https' could be added, that would be great.

Regards,
Kanhaiya

**Comment by richardbarran** [comment]
Hi,

Glad you've found a (temporary) solution. I've never tested a Photologue website under https, but I've quickly checked the codebase and I cannot see anywhere with 'http://' hardcoded. I would guess that the issue is at a higher level - somewhere in the Django settings, but it's hard to be precise.

**Comment by kanhaiyakumawat** [comment]
Thanks Much for your response Rich!!
