### ISSUE TITLE
not corrected read EXIF on Python3

### ISSUE THREAD

**Issue by AduchiMergen** [jdriscoll/django-photologue#142]
https://github.com/jdriscoll/django-photologue/blob/master/photologue/utils/EXIF.py#L1608
`data = f.read(12)`
 return bytestring but compared below with str and always return False at 1609 and 1615

**Comment by nim65s** [comment]
Ow, thanks, I had noticed that it was broken, but did not saw that it was because of my passage to python 3 :)

This library seems to have been ported: http://sourceforge.net/projects/exif-py-3/

**Comment by richardbarran** [comment]
Hi,
Photologue used to have a local copy of EXIF.py, I have switched to installing the (up to date) 3rd party library using pip - and it now works with Python 3.
At the same time I've tried to improve the code for processing EXIF data e.g. getting the date a photo was taken.
Hope that this is helpful - comments/feedback are always welcome.

**Comment by nim65s** [comment]
Thanks !

**Comment by richardbarran** [comment]
I am going to assume that this issue is fixed with the release of Photologue 3.4 - if any of you still have issues, please do not hesitate to re-open it.
