### ISSUE TITLE
django 1.9.1, python 2.7.10 - Field defines a relation with model 'PhotoEffect', which is either not installed, or is abstract.

### ISSUE THREAD

**Issue by jonathanmorgan** [jdriscoll/django-photologue#149]
Hello,

I just upgraded a django application to use django 1.9 (I went straight from 1.8 to 1.9.1, skipped 1.9.0 because of errors with other python packages).

This application has a model that extends ImageModel. The relevant code:

    from photologue.models import ImageModel

    ...

    class Image( ImageModel ):
    
        ORIENTATION_CHOICES = (
            ( 'tall', 'tall' ),
            ( 'wide', 'wide' ),
            ( 'square', 'square' ),
        )
    
        # fields
        slug = models.CharField( max_length = 255 )
        title = models.CharField( max_length = 255, blank = True, null = True )
        credit = models.CharField( max_length = 255, blank = True, null = True )
        caption = models.TextField( blank = True, null = True )
        pix_date = models.DateField( blank = True, null = True )
        pix_height = models.IntegerField()
        pix_width = models.IntegerField()
        pix_orientation = models.CharField( max_length = 255, choices = ORIENTATION_CHOICES )
        last_modified = models.DateField( auto_now = True )
    
    
        #----------------------------------------------------------------------
        # methods
        #----------------------------------------------------------------------
    
    
        def __unicode__( self ):
    
            # return reference
            string_OUT = ''
    
            # declare variables
            my_slug = ''
    
            # first output the start date and time (they are required).
            string_OUT = str( self.id )
    
            # try to get slug
            my_slug = self.slug
            if ( my_slug is not None ):
    
                string_OUT += " - " + my_slug
    
            #-- end check to see if we have a start date --#
    
            string_OUT += " - " + self.title
    
            return string_OUT
    
        #-- END method __unicode__() --#
    
    
    #= End Image Model 

When I installed django 1.9.1, I also installed django-photologue 3.4.1.

When I try to run the `manage.py migrate` command, I get the following error:

    ERRORS:
    events.Image.effect: (fields.E300) Field defines a relation with model 'PhotoEffect', which is either not installed, or is abstract.

And when I try to open the page for this Image model in the django Admin, I get:

    ValueError at /admin/events/image/
    Related model 'PhotoEffect' cannot be resolved

If I can provide more information that would be helpful, please let me know.  Any help or advice will be greatly appreciated.

Thanks,

Jonathan

**Comment by jonathanmorgan** [comment]
Just tested with django 1.8.8, and this issue is not present, so looks like this is related in some way to changes in django 1.9.

**Comment by jonathanmorgan** [comment]
I am going to make an install that just has the django demo app in it and see if I can reproduce this and another issue I'm having related to django-ajax-selects to see if this is reproducible in a clean project.

**Comment by richardbarran** [comment]
The last release of Photologue has buggy (missing!) migrations. Maybe this is interfering in some way with your project? It could be interesting to test your code against the current _master_ branch of Photologue.

**Comment by jonathanmorgan** [comment]
Ok.  I'll try installing from github into my virtualenv with 1.9.1 and see if that fixes it.

--

"The man with the new idea is a Crank until the idea succeeds."
- Mark Twain, from 'Following the Equator: A Journey Around the World'
(Sent from my iPhone)

**Comment by jonathanmorgan** [comment]
So, with django-photologue 3.5.dev0, with django 1.8.8, when you do "python manage.py migrate --list", it shows that two migrations are pending for photologue.  With django 1.9.1, when I run "python manage.py migrate --list", it gives the same error as before.

I am going to try making the tutorial app, will let you know if this persists there.  To test, I'll just add my Image class to the poll app, then make a PollImage that ties it to a poll in models.py.  More in a bit.

**Comment by bopbopmara** [comment]
Hi! I am using photologue in a project at work and when trying to migrate to Djago 1.9 I got a similar error from py.test: "Related model 'PhotoEffect' cannot be resolved". After seeing this issue report, I checked the manage.py migrate behavior and it is as described here.

Just a quick hint - patching directly the models.py in my virtualenv and changing ForeignKey fields from
effect = models.ForeignKey('PhotoEffect', ...) 
to
effect = models.ForeignKey('photologue.PhotoEffect', ...)
seems to fix these errors and make the code work.

I am not sure if I will have more time to investigate why and what change in Django 1.9 is the problem, but I hope that at least this could help fix things faster.

**Comment by richardbarran** [comment]
Hi bopbopmara - thanks for investigating this, and for suggesting a fix.
@jonathanmorgan - do you want to test this fix? If it works for you, we can apply it to Photologue.

**Comment by jonathanmorgan** [comment]
Happy to try.  Unfortunately right now, when I try to install django-photologue (django_photologue-3.5-py2.py3-none-any.whl), it gives me the following error:

    UnicodeEncodeError: 'ascii' codec can't encode character u'\xae' in position 28: ordinal not in range(128)

The full stack trace is below:

    $ pip install django-photologue
    Collecting django-photologue
      Downloading django_photologue-3.5-py2.py3-none-any.whl (283kB)
        100% |████████████████████████████████| 286kB 1.4MB/s 
    Exception:
    Traceback (most recent call last):
      File "/home/cvnc/.virtualenvs/cvnc-test/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
        status = self.run(options, args)
      File "/home/cvnc/.virtualenvs/cvnc-test/lib/python2.7/site-packages/pip/commands/install.py", line 294, in run
        requirement_set.prepare_files(finder)
      File "/home/cvnc/.virtualenvs/cvnc-test/lib/python2.7/site-packages/pip/req/req_set.py", line 334, in prepare_files
        functools.partial(self._prepare_file, finder))
      File "/home/cvnc/.virtualenvs/cvnc-test/lib/python2.7/site-packages/pip/req/req_set.py", line 321, in _walk_req_to_install
        more_reqs = handler(req_to_install)
      File "/home/cvnc/.virtualenvs/cvnc-test/lib/python2.7/site-packages/pip/req/req_set.py", line 491, in _prepare_file
        session=self.session)
      File "/home/cvnc/.virtualenvs/cvnc-test/lib/python2.7/site-packages/pip/download.py", line 825, in unpack_url
        session,
      File "/home/cvnc/.virtualenvs/cvnc-test/lib/python2.7/site-packages/pip/download.py", line 677, in unpack_http_url
        unpack_file(from_path, location, content_type, link)
      File "/home/cvnc/.virtualenvs/cvnc-test/lib/python2.7/site-packages/pip/utils/__init__.py", line 645, in unpack_file
        flatten=not filename.endswith('.whl')
      File "/home/cvnc/.virtualenvs/cvnc-test/lib/python2.7/site-packages/pip/utils/__init__.py", line 532, in unzip_file
        leading = has_leading_dir(zip.namelist()) and flatten
      File "/home/cvnc/.virtualenvs/cvnc-test/lib/python2.7/site-packages/pip/utils/__init__.py", line 247, in has_leading_dir
        prefix, rest = split_leading_dir(path)
      File "/home/cvnc/.virtualenvs/cvnc-test/lib/python2.7/site-packages/pip/utils/__init__.py", line 231, in split_leading_dir
        path = str(path)
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xae' in position 28: ordinal not in range(128)

I am away from my usual dev machine, but I did try to install on two different machines, one with CentOS 6, one with Ubuntu 15.10, and it failed this way on both machines (pip 7.1.2, setuptools 18.2).  Any idea what is going on?  Sorry for the trouble, and thanks for any help you can give.

Jon

**Comment by jonathanmorgan** [comment]
Hello again,

I installed the latest from github using pip (pip install git+https://github.com/jdriscoll/django-photologue.git) and:

- 1) that worked just fine where 3.5 didn't work.
- 2) in photologue/models.py in the site-packages for my virtualenv, I changed all instances of

        ForeignKey("PhotoEffect",

    to

        ForeignKey("photologue.PhotoEffect",

     using the command ":%s/ForeignKey('PhotoEffect',/ForeignKey('photologue.PhotoEffect',/g" in vi, and after that change, the command "python manage.py migrate --list" now works.

So, looks like the current contents of the github repository installs where 3.5 does not, and this change at least makes the problem with "python manage.py migrate --list" go away.  I can test it more thoroughly when I am once again able to use my dev server (Thursday morning), but that is progress.  Thanks for all of your help!

Jon

**Comment by richardbarran** [comment]
Hi @jonathanmorgan - I have tried to install Photologue 3.5 under Python 2.7, and, like you, I get a `UnicodeEncodeError`.
Serves me right for only testing it in Python 3!
I strongly suspect that it's caused by a new test file with a non-ascii filename; I will run some tests and I might have to prepare a new release.

**Comment by richardbarran** [comment]
Hi, I've just released Photologue 3.5.1 with fixes for both the issues that you've raised in this ticket. Hope that all is good now!

**Comment by jonathanmorgan** [comment]
I just installed and tested 3.5.1 and everything seems to be working well!  Thanks for the help!

**Comment by richardbarran** [comment]
Great to hear that everything is now working well :-)
