### ISSUE TITLE
Backport release of 3.1.x

### ISSUE THREAD

**Issue by hedleyroos** [jdriscoll/django-photologue#151]
django-model-utils 2.4 has deprecated the PassthroughManager. https://github.com/jdriscoll/django-photologue/blob/3.1.1/requirements.txt has a lax pin django-model-utils>=2.2. If I create a PR to constrain it to django-model-utils>=2.2,<2.4 would you release 3.1.2?

**Comment by richardbarran** [comment]
Yes I would - please send in a PR.

**Comment by richardbarran** [comment]
PassthroughManager is no longer used, as Django now supports this functionality natively; so I guess that this requirement is obsolete.
