### ISSUE TITLE
Hello I can not create watermark, when create give this error.

### ISSUE THREAD

**Issue by cloudzhong** [jdriscoll/django-photologue#153]
TypeError at /admin/photologue/watermark/add/
integer argument expected, got float
Request Method:	POST
Request URL:	https://django-cloudzhong-1.c9users.io/admin/photologue/watermark/add/
Django Version:	1.9.2
Exception Type:	TypeError
Exception Value:	
integer argument expected, got float
Exception Location:	/home/ubuntu/workspace/PIL/Image.py in paste, line 1330
Python Executable:	/usr/bin/python2
Python Version:	2.7.6
Python Path:	
['/home/ubuntu/workspace',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/pymodules/python2.7']
Server time:	Fri, 19 Feb 2016 03:36:07 +0000

**Comment by richardbarran** [comment]
Hi - thanks for the bug report; it was fixed in Photologue 3.4.
Upgrade your version of Photologue and you won't have this issue ;-)
