### ISSUE TITLE
When using delete from a set, the image files are not removed

### ISSUE THREAD

**Issue by tluyben** [jdriscoll/django-photologue#154]
When deleting from, for instance, Django admin, the images are not removed; I think pre_delete or post_delete signals should be used instead of just calling delete like is done now?

**Comment by richardbarran** [comment]
There used to be a bug that meant that (sometimes) image files were not removed - what version of Photologue are you using?

**Comment by richardbarran** [comment]
Closing ticket as inactive for long time.
