### ISSUE TITLE
Why photo title has to be unique accross all galleries and sites?

### ISSUE THREAD

**Issue by ramast** [jdriscoll/django-photologue#158]
```
class photo(imagemodel):
    title = models.CharField(_('title'), max_length=250, unique=true)
```
Why does a photo require a unique title? Its difficult to tell the user "Sorry, this title has already been taken, think of something else"

**Comment by richardbarran** [comment]
That's a good question.
To me it seems 'obvious' that a photo title should be unique. However, I can conceive that there are use cases where it would be a limitation.
I wouldn't be too keen on removing the 'unique' constraint entirely - I've been maintaining this project for approx. 4 years and it's the first time that anyone mentions this, so I guess that the current setup is suitable for most users! :-)
That said, if there's way to make this configurable, I'd certainly consider adding it as a feature. E.g. maybe an idea would be to remove the 'unique' constraint from the database level, and instead enforce it in the clean() method on Photo. Then we could have a setting to switch it on/switch it off.
That's just an idea - there's probably a far better way to implement it, and I'm open to suggestions!

**Comment by ramast** [comment]
Now that I am thinking about it, I realize the project is meant to provide galleries to be managed by admins and viewed by users.

I am trying to (ab)use it to provide galleries that both admins and users can do modifications to it (upload, delete, edit) based on their authorization (admins and gallery owner does anything, others can view only)

Unless there is plans to switch the project's goal from single user galleries to multi user, I'd say my issue is irrelevant.

**Comment by richardbarran** [comment]
I think it's best to stick to the most common scenario - single user galleries. So I'm going to close this ticket. Thanks for your input!
