### ISSUE TITLE
no such table: photologue_photo_sites

### ISSUE THREAD

**Issue by maxLoveCode** [jdriscoll/django-photologue#160]
Hi, I just want to build a instant gallery in my website.
After I add the photo/gallery to the server, it returns:

OperationalError at /admin/photologue/photo/add/
no such table: photologue_photo_sites
Request Method:	POST
Request URL:	http://127.0.0.1:8000/admin/photologue/photo/add/
Django Version:	1.9.5
Exception Type:	OperationalError
Exception Value:	
no such table: photologue_photo_sites
Exception Location:	//anaconda/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py in execute, line 323
Python Executable:	//anaconda/bin/python
Python Version:	2.7.12

**Comment by richardbarran** [comment]
Hi,
Could you post here:
- the output from 'python manage.py migrate --list'
- what version of django-photologue are you using.

**Comment by maxLoveCode** [comment]
- Migration List

admin
 [X] 0001_initial
 [X] 0002_logentry_remove_auto_add
auth
 [X] 0001_initial
 [X] 0002_alter_permission_name_max_length
 [X] 0003_alter_user_email_max_length
 [X] 0004_alter_user_username_opts
 [X] 0005_alter_user_last_login_null
 [X] 0006_require_contenttypes_0002
 [X] 0007_alter_validators_add_error_messages
blog
 [X] 0001_initial
contenttypes
 [X] 0001_initial
 [X] 0002_remove_content_type_name
homepage
 (no migrations)
photologue
 [X] 0001_initial
 [X] 0002_photosize_data
 [X] 0003_auto_20140822_1716
 [X] 0004_auto_20140915_1259
 [X] 0005_auto_20141027_1552
 [X] 0006_auto_20141028_2005
 [X] 0007_auto_20150404_1737
 [X] 0008_auto_20150509_1557
 [X] 0009_auto_20160102_0904
 [X] 0010_auto_20160105_1307
sessions
 [X] 0001_initial
sites
 [X] 0001_initial
 [X] 0002_alter_domain_unique

-----------------------------------------------------------------------------

Django-photologue version : 3.5.1

**Comment by maxLoveCode** [comment]
Solved.

I have totally removed the db.sqlite3 file from the project, then migrate again and it works. 
But it clear all the database and just recreate one.
