### ISSUE TITLE
How to use @login_reqired decorator to the "class GalleryArchiveIndexView"

### ISSUE THREAD

**Issue by dlwxxxdlw** [jdriscoll/django-photologue#163]
**Hello! First of all , thank you for making such wonderfull App.**

Here is my problem: usually , the code in view.py is like this below
```python
@login_required
def logout(request):
    staticClass.value = None
    auth.logout(request)
    blogs = Blog.objects.all()
    tags = Tag.objects.all()
    return render(request,'sblog/blog_list.html',{"blogs":blogs,"tags":tags})
```
**It is a method.  
But in photologue's view.py its like :**
```python
class GalleryDateDetailView(GalleryDateView, DateDetailView):
    pass


class GalleryArchiveIndexView(GalleryDateView, ArchiveIndexView):
    pass


class GalleryDayArchiveView(GalleryDateView, DayArchiveView):
    pass


class GalleryMonthArchiveView(GalleryDateView, MonthArchiveView):
```
**They're all "class" !!! 囧rz**
Here comes the question , How can I use "@login_required" to such class ? I have no idea , please help me out .

**Comment by nim65s** [comment]
Hi,

For classes, you can't use decorators, but you can use mixins, like this one for required login:
https://docs.djangoproject.com/fr/1.10/topics/auth/default/#the-loginrequired-mixin

**Comment by dlwxxxdlw** [comment]
Thanks ! It will solve my problem properly , I'm going to close this issue.
