### ISSUE TITLE
Displaying Images uploaded in template

### ISSUE THREAD

**Issue by PhorlarinDjango** [jdriscoll/django-photologue#166]
Hi, I have followed the instructions on how to install photologue. I am able to upload photos from my django admin. Only issue is after searching and trying different things, I still can't quite figure out how to display the pictures I uploaded in my templates. Are there special template tags required? Please it would be helpful if you could show me how to display images uploaded with photologue in my templates. Thank you.

**Comment by richardbarran** [comment]
Sorry - this is something that is not in the docs - it's forever on the "TODO" list.
[Take a look at the example templates](https://github.com/jdriscoll/django-photologue/blob/master/photologue/templates/photologue/photo_list.html#L16) - if you have a 'photo' instance as a template variable, then `{{ photo.get_thumbnail_url }}` will get the url of the thumbnail (photosize) called 'thumbnail'. Likewise, if you've defined a Photosize called 'display' then `{{ photo.get_display_url }}` will fetch it.

**Comment by PhorlarinDjango** [comment]
Thanks for your help here Richard, I have been able to solve it using the
sample template you directed me to. Thank you.
