### ISSUE TITLE
First paragraph of docs

### ISSUE THREAD

**Issue by guettli** [jdriscoll/django-photologue#168]
Hi this is at the top of the docs:

{{{
The Photologue documentation is being transferred from a Google Code wiki to a Sphinx-generated setup (if you’re reading this at readthedocs.org, then you’re looking at these docs).

This documentation is accurate and up-to-date (hopefully!); the old docs on the Google Code wiki are extensive but have not been updated in a long time.
}}}

I guess you (the developers) never look at the docs, but new comers do.

Is this warning still useful today?

**Comment by richardbarran** [comment]
No, it's out of date :-)
I will remove it from the docs - thanks for the heads-up.
