### ISSUE TITLE
OperationalError while adding Gallery

### ISSUE THREAD

**Issue by RodrigoToledoA** [jdriscoll/django-photologue#174]
Hi there, i'm using django 1.10 and photologue 3.6. When I save a new gallery it raises the error.
It was all functionally till I installed django 1.11 and the errors started to appear. I downgraded django and this error happened:

`OperationalError: no such column: photologue_gallery_photos.sort_value`

**Comment by richardbarran** [comment]
Hi,
I haven't tested Photologue with Django 1.11 - so there might be errors. In particular, some of the 3rd party libraries might need to be upgraded to versions that are compatible with Django 1.11. But I haven't done any work on this yet.
I'm not sure why you get errors when you downgrade Django; can you run `python manage.py showmigrations` and list the output here please?

**Comment by RodrigoToledoA** [comment]
I made a backup database from when it was functional and now I'm using that one without any errors... Kind of weird but it works...

'python manage.py showmigrations
photologue
 [X] 0001_initial
 [X] 0002_photosize_data
 [X] 0003_auto_20140822_1716
 [X] 0004_auto_20140915_1259
 [X] 0005_auto_20141027_1552
 [X] 0006_auto_20141028_2005
 [X] 0007_auto_20150404_1737
 [X] 0008_auto_20150509_1557
 [X] 0009_auto_20160102_0904
 [X] 0010_auto_20160105_1307
'
That are the ones from photologue

**Comment by richardbarran** [comment]
Hi,
Glad to hear that you got your website working from a backup.
Reverting to an earlier version of Django is a very unusual situation - and the issue has gone away - so I'm going to mark this ticket 'closed'.
