### ISSUE TITLE
Add new language for start translate

### ISSUE THREAD

**Issue by DmytroLitvinov** [jdriscoll/django-photologue#178]
Hi there. I have requested new language(Ukrainian) at [transifex](https://www.transifex.com/richardbarran/django-photologue/). Could you please accept request that I started to translate and add translated text into system.

**Comment by richardbarran** [comment]
Language added and invitation sent on Transifex.
Once you've added the translated string, please let me know if you want a micro-release of Photologue with the new language.

**Comment by DmytroLitvinov** [comment]
@richardbarran Hi :) I have translated in Ukrainian. Could you please accept them in master branch?

**Comment by richardbarran** [comment]
@DmytroLitvinov - Thanks for the translation. I notice that there are 4 strings that have not been translated: https://www.transifex.com/richardbarran/django-photologue/viewstrings/#uk/core/68357403?translated=no

Do you want to translate these remaining strings, or can I proceed with a micro-release of Photologue that includes the 145 strings that you have already translated?

**Comment by DmytroLitvinov** [comment]
I'll translate it today. But also I think I have not correct translate some of words, because in Ukrainian 7 grammatical case. I'll notify you here

I have just translated it, but also I think in some places it is not correct translated, so I'll test it, when it will be applied to master branch, so I can test it at website. Also, in Ukrainian 7 grammatical case. Waiting for commit at master.
Thanks for notify and for the app. :1st_place_medal:

**Comment by richardbarran** [comment]
Hi @DmytroLitvinov - your translations are now in the master branch.

**Comment by DmytroLitvinov** [comment]
Thank you very much :+1:
