### ISSUE TITLE
Broken in Django 2.0

### ISSUE THREAD

**Issue by isolationism** [jdriscoll/django-photologue#179]
```
  File "/raid/projects/cso/csoweb/lib/python3.4/site-packages/photologue/models.py", line 17, in <module>
    from django.core.urlresolvers import reverse
ImportError: No module named 'django.core.urlresolvers'
```

I'm sure there are other errors as well, but I decide to try my application with the latest release and quickly rolled back to 1.11.

**Comment by richardbarran** [comment]
Hi,
Thanks for the heads-up - I didn't realise that Django 2.0 had been release today!
I've done [a bit of work on a separate branch to fix some deprecation warnings](https://github.com/jdriscoll/django-photologue/tree/django20) and prepare for 2.0 - maybe it's already compatible with the latest release!

**Comment by richardbarran** [comment]
Hi,
I have released a new version of Django-photologue that is compatible with Django 2.0. Please give it a try and let me know if you notice any issues!
