### ISSUE TITLE
TemplateDoesNotExist at /photologue/gallery/

### ISSUE THREAD

**Issue by TopolinoHackerino** [jdriscoll/django-photologue#183]
TemplateDoesNotExist -> base.html

> In template /Users/topolinohakerino/PycharmProjects/hakerino_website/venv/lib/python3.6/site-packages/photologue/templates/photologue/root.html, error at line 1

I have done a clean install on a Django 2.0, but I'm getting this error. I have checked into the photologue/templates/photologue/ and is missing the base.html.
I have tried to add it manually with a copy of the file in this repo, but no luck.

Have someone a fix?

thank you

**Comment by TopolinoHackerino** [comment]
I think the problem is within the "bootstrap"-idea delivered with photolouge. 
I use UIkit, after drain of bootstrap classes, I have fixed with coping all the files from templates/photolouge and extending with personal index file. I think documentation need update.

issue doesn't persist can be closed

Thank's to the the owner, very useful app!

**Comment by GuillaumeDesforges** [comment]
Same issue here.
