### ISSUE TITLE
add text from README to front page of docs?

### ISSUE THREAD

**Issue by NickleDave** [jdriscoll/django-photologue#188]
Hi django-photologue devs,

I found the library from the django-packages site and wasn't sure whether the package would do what I wanted to. Then I googled the actual Github repo and found all the background info that's in the README.md--turns out it does do what I needed, and looks like it does it well.

So the info along with the demo site and examples is super helpful, but maybe it would be good to also have it on the front page of the docs? Literally to just copy and paste it so someone who finds the docs first instead of the Github repo will know at a high level what the package does?

I could submit a PR to do just that if you agree it would help newbies get oriented.

Thanks,
David

**Comment by richardbarran** [comment]
Hi NickleDave,
It sounds like a good idea; I wonder if it's possible to automatically synchronise this page in the docs, and the README?

In any case, a PR will be welcome.
