### ISSUE TITLE
Photo template tags not displaying pictures

### ISSUE THREAD

**Issue by peter-doherty** [jdriscoll/django-photologue#191]
I've the same issue as [previously reported by another user](https://github.com/jdriscoll/django-photologue/issues/166) but can't seem to resolve my issue. I am using the templates from the example project and appear to have the correct setup in admin. Screenshots below. The issue is that the code below does not seem to register an object list.

This issue comes up when I want to use my own templates.

Any help would be greatly appreciated!

Code:

```
{% if object_list %}
		<div class="row col-lg-12">
		    {% for photo in object_list %}
		        <a href="{{ photo.get_absolute_url }}">
		             <img src="{{ photo.get_thumbnail_url }}" class="thumbnail" alt="{{ photo.title }}">
		        </a>
		    {% endfor %}
		</div>
	{% else %}
		<div class="row col-lg-12">
			<div class="row">{% trans "No photos were found" %}.</div>
		</div>
	{% endif %}
```

Admin Setup:
![image](https://user-images.githubusercontent.com/22255078/44799603-5aaa2b80-ab82-11e8-9f5c-0853ad5cb48d.png)

Output:
![image](https://user-images.githubusercontent.com/22255078/44799655-79102700-ab82-11e8-8cb6-8237f31372a4.png)

**Comment by richardbarran** [comment]
Do the photo thumbnails display correctly if you use the provided Photologue templates? There is only an issue when you use your own template?

**Comment by peter-doherty** [comment]
I found a "workaround" for my issue. I start with the Photologue repo and add in the rest of my app around that. As opposed to starting from my app and then inserting Photologue. I must be missing something fundamental in my setup. My conclusion is that the issue is on me, not the codebase.
