### ISSUE TITLE
Makemigrations create a new migration

### ISSUE THREAD

**Issue by Arussil** [jdriscoll/django-photologue#194]
Hi,

I've installed photologue 3.8.1 from PyPi and discovered that using the makemigrations command create a new migration:

`Migrations for 'photologue':
  venv/lib/python3.7/site-packages/photologue/migrations/0011_auto_20181211_1008.py
    - Alter field filters on photoeffect`

this made so that my app would use it as a dependencies when using photologue Fields breaking a new installation as the referenced migration does not exist on the repo.

Thanks,

**Comment by richardbarran** [comment]
Hi,
Apologies for the slow response.
Yes, there was a migration missing - I'm not sure why, as the field changed by the migration has not been touched in several years. Maybe some internal bug in the Django migrations code. Anyway, it's fixed now.
Thanks for the bug report!
