### ISSUE TITLE
When creating a gallery page freezes

### ISSUE THREAD

**Issue by tbazadaykin** [jdriscoll/django-photologue#87]
if the Photologue uploaded a lot of photos when you create a gallery page the browser freezes. the problem is that the list for the "Photos" are loaded ALL the photos. and if they are 30,000?

**Comment by richardbarran** [comment]
The latest release of django-sortedm2m includes a performance boost that should help make this less of an issue.
I've updated photologue to use this latest release, so I think we can close this ticket now.
